//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Store.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class analysts_dbEntities : DbContext
    {
        public analysts_dbEntities()
            : base("name=analysts_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client_type_nv> client_type_nv { get; set; }
        public virtual DbSet<employee_nv> employee_nv { get; set; }
        public virtual DbSet<owner_nv> owner_nv { get; set; }
        public virtual DbSet<pet_nv> pet_nv { get; set; }
        public virtual DbSet<pet_type_nv> pet_type_nv { get; set; }
        public virtual DbSet<service_nv> service_nv { get; set; }
        public virtual DbSet<service_type_nv> service_type_nv { get; set; }
    }
}
