//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class owner_nv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public owner_nv()
        {
            this.pet_nv = new HashSet<pet_nv>();
        }
    
        public int id { get; set; }
        public long owner_national_id { get; set; }
        public string owner_name { get; set; }
        public string owner_phone_number { get; set; }
        public string owner_email { get; set; }
        public int client_type_id { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual client_type_nv client_type_nv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pet_nv> pet_nv { get; set; }
    }
}
