//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_nv
    {
        public int id { get; set; }
        public int service_type_id { get; set; }
        public Nullable<System.DateTime> service_date { get; set; }
        public int employee_id { get; set; }
        public int pet_id { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual employee_nv employee_nv { get; set; }
        public virtual pet_nv pet_nv { get; set; }
        public virtual service_type_nv service_type_nv { get; set; }
    }
}
